-- InstaAutoPost — Development RLS Policies (Reference Only)
-- File: supabase/policies/instaautopost_dev_rls_policies.sql
--
-- !! NOT THE OPERATIONAL SOURCE OF TRUTH !!
--
-- Dev RLS policies are now applied through the migration:
--   supabase/migrations/20260516001000_add_instaautopost_dev_rls_policies.sql
--
-- This file is kept as a human-readable reference only.
-- Do not apply this file directly — use `supabase db push` to apply all migrations.
