#!/usr/bin/env python3
"""
InstaAutoPost Scheduler
Generates ig_publishing_queue rows for draft/approved content using randomized
time windows. All scheduled_at values are computed and written during --execute;
the publisher worker never picks times at runtime.

Dry-run by default. Use --execute to insert rows into Supabase.
Does NOT publish to Instagram, trigger GitHub Actions, or touch Storage.

Usage example:
  python3 scripts/schedule_draft_content.py \
    --first-in-minutes 5 \
    --end-date 2026-07-01 \
    --windows "07:00:00-09:00:00,12:00:00-14:00:00,18:00:00-20:00:00" \
    --unique-clock-times \
    --randomize-content \
    --seed 23 \
    --title-prefixes "Reel,Video Post,Carousel" \
    --limit 9

Add --execute to insert rows. The exact same --seed produces the same schedule
on every run (dry-run or live), so you can preview before committing.
"""

import argparse
import os
import random
import sys
import logging
from datetime import datetime, timedelta, date as date_type, timezone
from zoneinfo import ZoneInfo
from typing import Optional

from supabase import create_client, Client

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
SCRIPT_NAME = "schedule_draft_content.py"
DEFAULT_TZ_NAME = "America/New_York"
DEFAULT_WINDOWS_STR = "07:00:00-09:00:00,12:00:00-14:00:00,18:00:00-20:00:00"
MAX_ATTEMPTS = 3
QUEUE_NOTES = f"generated by {SCRIPT_NAME}"

# Media type round-robin priority (case-insensitive)
MEDIA_TYPE_ORDER = {"reel": 0, "video": 1, "carousel": 2}

# Queue statuses that prevent re-scheduling the same content_id.
# draft, failed, cancelled are NOT blocking — they are inactive or exhausted.
BLOCKING_STATUSES = ("scheduled", "ready", "processing", "published", "retry_scheduled")

# Max retries to find a unique HH:MM:SS within a single window
_UNIQUE_RETRY_CAP = 1000

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%SZ",
    stream=sys.stdout,
)
log = logging.getLogger("scheduler")


# ---------------------------------------------------------------------------
# Supabase
# ---------------------------------------------------------------------------
def get_supabase() -> Client:
    url = os.environ.get("SUPABASE_URL", "").strip()
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "").strip()
    if not url or not key:
        log.error("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required")
        sys.exit(1)
    return create_client(url, key)


# ---------------------------------------------------------------------------
# Data fetching
# ---------------------------------------------------------------------------
def fetch_eligible_content(supabase: Client) -> list[dict]:
    """All draft/approved content, oldest first."""
    result = (
        supabase.table("ig_content_library")
        .select("id, title, media_type, content_status, created_at")
        .in_("content_status", ["draft", "approved"])
        .order("created_at", desc=False)
        .execute()
    )
    return result.data or []


def fetch_blocked_content_ids(supabase: Client) -> set[str]:
    """content_ids that already have an active or published queue row."""
    result = (
        supabase.table("ig_publishing_queue")
        .select("content_id")
        .in_("queue_status", list(BLOCKING_STATUSES))
        .execute()
    )
    return {row["content_id"] for row in (result.data or [])}


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------
def _parse_hms(t: str) -> tuple[int, int, int]:
    """Parse HH:MM:SS into (hour, minute, second)."""
    parts = t.strip().split(":")
    if len(parts) != 3:
        log.error(f"Invalid time {t!r} — expected HH:MM:SS")
        sys.exit(1)
    try:
        h, m, s = int(parts[0]), int(parts[1]), int(parts[2])
    except ValueError:
        log.error(f"Non-integer in time {t!r}")
        sys.exit(1)
    if not (0 <= h <= 23 and 0 <= m <= 59 and 0 <= s <= 59):
        log.error(f"Time out of range: {t!r}")
        sys.exit(1)
    return h, m, s


# Each window is (start_h, start_m, start_s, end_h, end_m, end_s)
Window = tuple[int, int, int, int, int, int]


def parse_windows(windows_str: str) -> list[Window]:
    """
    Parse 'HH:MM:SS-HH:MM:SS,...' into a sorted list of Window tuples.
    End time must be strictly after start time.
    """
    result: list[Window] = []
    for raw in windows_str.split(","):
        raw = raw.strip()
        # Hyphen separates start and end; split on the hyphen that follows a digit
        # (i.e., the one between HH:MM:SS and HH:MM:SS, not inside the time)
        dash_idx = raw.index("-", 8)  # earliest possible dash is after 'HH:MM:SS'
        h1, m1, s1 = _parse_hms(raw[:dash_idx])
        h2, m2, s2 = _parse_hms(raw[dash_idx + 1:])
        start_sec = h1 * 3600 + m1 * 60 + s1
        end_sec   = h2 * 3600 + m2 * 60 + s2
        if end_sec <= start_sec:
            log.error(f"Window end must be strictly after start: {raw!r}")
            sys.exit(1)
        result.append((h1, m1, s1, h2, m2, s2))
    return sorted(result, key=lambda w: w[0] * 3600 + w[1] * 60 + w[2])


# ---------------------------------------------------------------------------
# Slot generation
# ---------------------------------------------------------------------------
def generate_window_slots(
    rng: random.Random,
    tz: ZoneInfo,
    start_date: date_type,
    end_date: date_type,           # exclusive
    windows: list[Window],
    unique_clock_times: bool,
    reserved_hms: Optional[tuple[int, int, int]] = None,
) -> list[datetime]:
    """
    Generate exactly one randomized slot per window per day, from start_date up
    to (not including) end_date.  All randomness comes from `rng`; with the same
    seed the output is identical on every call.

    If unique_clock_times is True, no two output slots share the same HH:MM:SS
    (the reserved_hms from --first-in-minutes is also excluded from the pool).
    """
    used_hms: set[tuple[int, int, int]] = set()
    if reserved_hms is not None:
        used_hms.add(reserved_hms)

    slots: list[datetime] = []
    current = start_date
    while current < end_date:
        for h1, m1, s1, h2, m2, s2 in windows:
            start_sec  = h1 * 3600 + m1 * 60 + s1
            end_sec    = h2 * 3600 + m2 * 60 + s2
            window_sec = end_sec - start_sec   # seconds available in this window

            found = False
            retries = min(window_sec, _UNIQUE_RETRY_CAP)
            for _ in range(retries):
                offset    = rng.randint(0, window_sec - 1)
                total_sec = start_sec + offset
                h = total_sec // 3600
                m = (total_sec % 3600) // 60
                s = total_sec % 60
                hms = (h, m, s)

                if not unique_clock_times or hms not in used_hms:
                    used_hms.add(hms)
                    slots.append(
                        datetime(current.year, current.month, current.day,
                                 h, m, s, tzinfo=tz)
                    )
                    found = True
                    break

            if not found:
                log.warning(
                    f"Could not find unique HH:MM:SS in window "
                    f"{h1:02d}:{m1:02d}-{h2:02d}:{m2:02d} "
                    f"for {current} after {retries} attempts — slot skipped"
                )
        current += timedelta(days=1)

    return sorted(slots)


def round_robin_sort(content: list[dict]) -> list[dict]:
    """
    Interleave content: REEL → VIDEO → CAROUSEL → REEL → …
    Within each type, preserves created_at ascending order.
    Unknown types come last.
    """
    buckets: dict[int, list[dict]] = {}
    for item in content:
        mt = (item.get("media_type") or "").lower()
        priority = MEDIA_TYPE_ORDER.get(mt, 99)
        buckets.setdefault(priority, []).append(item)

    for bucket in buckets.values():
        bucket.sort(key=lambda x: x.get("created_at", ""))

    ordered_keys = sorted(buckets.keys())
    result: list[dict] = []
    while any(buckets[k] for k in ordered_keys):
        for k in ordered_keys:
            if buckets[k]:
                result.append(buckets[k].pop(0))
    return result


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
def _trunc(s: str, width: int) -> str:
    s = str(s)
    if len(s) > width:
        return s[: width - 1] + "…"
    return s.ljust(width)


def print_preview(rows: list[dict], tz: ZoneInfo) -> None:
    headers = ["#", "Title", "Type", "Status", "Scheduled (NY)", "Scheduled (UTC)", "Action"]
    widths  = [ 3,   32,      10,     10,        26,               24,                26    ]
    sep     = "  ".join("─" * w for w in widths)
    hdr     = "  ".join(_trunc(h, widths[i]) for i, h in enumerate(headers))

    print()
    print(f"  {hdr}")
    print(f"  {sep}")

    for idx, row in enumerate(rows, 1):
        raw = row.get("scheduled_at_utc")
        if raw:
            utc_dt = datetime.fromisoformat(raw)
            if utc_dt.tzinfo is None:
                utc_dt = utc_dt.replace(tzinfo=timezone.utc)
            sched_ny_str  = utc_dt.astimezone(tz).strftime("%b %d %H:%M:%S %Z")
            sched_utc_str = utc_dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        else:
            sched_ny_str = sched_utc_str = "—"

        cols = [
            str(idx),
            row.get("title") or "—",
            (row.get("media_type") or "—").upper(),
            row.get("content_status") or "—",
            sched_ny_str,
            sched_utc_str,
            row.get("action") or "—",
        ]
        print("  " + "  ".join(_trunc(c, widths[i]) for i, c in enumerate(cols)))

    print()


def print_summary(
    *,
    total_eligible: int,
    skipped_prefix: int,
    skipped_queued: int,
    selected_count: int,
    slot_count: int,
    unused_slots: int,
    no_slot: int,
    to_schedule: int,
    inserted: int,
    failed: int,
    first_slot: Optional[datetime],
    last_slot: Optional[datetime],
    tz: ZoneInfo,
    execute: bool,
    times_unique: bool,
) -> None:
    print("=" * 64)
    print("SUMMARY")
    print("=" * 64)
    print(f"  Eligible content (draft/approved):    {total_eligible}")
    print(f"  Excluded by title-prefix filter:      {skipped_prefix}")
    print(f"  Already queued (skipped):             {skipped_queued}")
    print(f"  Selected for scheduling:              {selected_count}")
    print(f"  Generated window slots:               {slot_count}")
    print(f"  Unused slots (slots > items):         {unused_slots}")
    print(f"  Skipped — no slot in window:          {no_slot}")

    if execute:
        print(f"  Inserted successfully:                {inserted}")
        print(f"  Failed (insert error):                {failed}")
    else:
        print(f"  Would schedule (dry run):             {to_schedule}")

    if first_slot:
        print(f"  First scheduled (NY):                 "
              f"{first_slot.astimezone(tz).strftime('%Y-%m-%d %H:%M:%S %Z')}")
        print(f"  First scheduled (UTC):                "
              f"{first_slot.astimezone(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")
    if last_slot and last_slot != first_slot:
        print(f"  Last scheduled (NY):                  "
              f"{last_slot.astimezone(tz).strftime('%Y-%m-%d %H:%M:%S %Z')}")
        print(f"  Last scheduled (UTC):                 "
              f"{last_slot.astimezone(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")

    unique_str = (
        "YES — all HH:MM:SS values are unique"
        if times_unique
        else "NO  — duplicate HH:MM:SS detected!"
    )
    print(f"  HH:MM:SS uniqueness:                  {unique_str}")

    if not execute:
        print()
        print("  [DRY RUN] No rows inserted. Re-run with --execute to apply.")

    print("=" * 64)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Schedule draft/approved content into ig_publishing_queue using "
            "randomized time windows. All scheduled_at values are precomputed "
            "and fixed at insert time. Dry-run by default; use --execute to insert rows. "
            "Does NOT publish to Instagram, trigger GitHub Actions, or touch Storage."
        )
    )
    parser.add_argument(
        "--title-prefixes", metavar="PREFIX,...",
        help=(
            'Only include content whose title starts with one of these prefixes '
            '(e.g. "Reel,Video Post,Carousel"). Others are excluded.'
        ),
    )
    parser.add_argument(
        "--end-date", metavar="YYYY-MM-DD",
        help=(
            "Slot generation end date, exclusive (e.g. 2026-07-01 means up to "
            "June 30). Defaults to 30 days from today."
        ),
    )
    parser.add_argument(
        "--windows", default=DEFAULT_WINDOWS_STR, metavar="HH:MM:SS-HH:MM:SS,...",
        help=(
            "Comma-separated time windows per day in America/New_York. "
            f"Default: {DEFAULT_WINDOWS_STR}."
        ),
    )
    parser.add_argument(
        "--unique-clock-times", action="store_true",
        help="Enforce that no two scheduled posts share the same HH:MM:SS.",
    )
    parser.add_argument(
        "--randomize-content", action="store_true",
        help="Shuffle content selection order using --seed (requires --seed).",
    )
    parser.add_argument(
        "--seed", type=int, metavar="N",
        help=(
            "Integer seed for deterministic pseudo-random generation. "
            "The same seed produces the same schedule on every run. "
            "Required with --randomize-content."
        ),
    )
    parser.add_argument(
        "--first-in-minutes", type=int, metavar="N",
        help=(
            "Override the first slot to now + N minutes. "
            "Remaining items use window slots strictly after that time."
        ),
    )
    parser.add_argument(
        "--limit", type=int, metavar="N",
        help="Cap the number of content items to schedule.",
    )
    parser.add_argument(
        "--execute", action="store_true",
        help="Insert rows into Supabase. Default is dry-run only.",
    )
    args = parser.parse_args()

    # --- Validate args -------------------------------------------------------
    if args.limit is not None and args.limit < 1:
        log.error("--limit must be >= 1")
        sys.exit(1)
    if args.first_in_minutes is not None and args.first_in_minutes < 0:
        log.error("--first-in-minutes must be >= 0")
        sys.exit(1)
    if args.randomize_content and args.seed is None:
        log.error(
            "--seed is required when --randomize-content is used "
            "(ensures dry-run and --execute produce identical order)"
        )
        sys.exit(1)

    # --- Setup ---------------------------------------------------------------
    tz = ZoneInfo(DEFAULT_TZ_NAME)
    now_local = datetime.now(tz)

    # Seed: if not provided, pick one and print it so the user can reproduce
    seed = args.seed
    if seed is None:
        seed = random.randint(0, 2**31 - 1)
        log.warning(
            f"No --seed provided. Using seed={seed}. "
            f"Re-run with --seed {seed} to reproduce this exact schedule."
        )
    rng = random.Random(seed)

    windows = parse_windows(args.windows)

    if args.end_date:
        try:
            end_date = date_type.fromisoformat(args.end_date)
        except ValueError:
            log.error(f"Invalid --end-date {args.end_date!r} — expected YYYY-MM-DD")
            sys.exit(1)
    else:
        end_date = (now_local + timedelta(days=30)).date()

    start_date = now_local.date()

    if end_date <= start_date:
        log.error(f"--end-date {end_date} must be after today ({start_date})")
        sys.exit(1)

    # --- Header --------------------------------------------------------------
    mode_label = "LIVE — WILL INSERT ROWS" if args.execute else "DRY RUN"
    log.info(f"InstaAutoPost Scheduler | mode={mode_label} | tz={DEFAULT_TZ_NAME}")
    log.info(f"  seed={seed}  start={start_date}  end_date={end_date} (exclusive)")
    log.info(f"  windows={args.windows}")
    log.info(
        f"  title_prefixes={args.title_prefixes or 'all'}  "
        f"limit={args.limit or 'none'}"
    )
    log.info(
        f"  unique_clock_times={args.unique_clock_times}  "
        f"randomize_content={args.randomize_content}"
    )
    if args.first_in_minutes is not None:
        override_dt = now_local + timedelta(minutes=args.first_in_minutes)
        log.info(
            f"  first_in_minutes={args.first_in_minutes} "
            f"→ {override_dt.strftime('%Y-%m-%d %H:%M:%S %Z')}"
        )

    # --- Fetch ---------------------------------------------------------------
    supabase = get_supabase()

    log.info("Fetching eligible content from ig_content_library...")
    all_content = fetch_eligible_content(supabase)
    log.info(f"  {len(all_content)} draft/approved item(s) found")

    log.info("Checking ig_publishing_queue for already-scheduled content...")
    blocked_ids = fetch_blocked_content_ids(supabase)
    log.info(f"  {len(blocked_ids)} content_id(s) already in an active queue state")

    # --- Filter: blocked -----------------------------------------------------
    skipped_queued = [c for c in all_content if c["id"] in blocked_ids]
    unblocked = [c for c in all_content if c["id"] not in blocked_ids]

    # --- Filter: title prefixes ----------------------------------------------
    skipped_prefix_count = 0
    if args.title_prefixes:
        prefixes = [p.strip() for p in args.title_prefixes.split(",") if p.strip()]
        before = len(unblocked)
        unblocked = [
            c for c in unblocked
            if any(c.get("title", "").startswith(p) for p in prefixes)
        ]
        skipped_prefix_count = before - len(unblocked)
        log.info(
            f"  {skipped_prefix_count} item(s) excluded by title-prefix filter "
            f"(kept prefixes: {prefixes})"
        )

    # --- Order content -------------------------------------------------------
    if args.randomize_content:
        rng.shuffle(unblocked)
        log.info(f"  Content order randomized with seed={seed}")
    else:
        unblocked = round_robin_sort(unblocked)

    if args.limit is not None:
        unblocked = unblocked[: args.limit]

    log.info(f"  {len(unblocked)} item(s) selected for scheduling")

    # --- Generate window slots -----------------------------------------------
    # Reserve the first_in_minutes HH:MM:SS so the window generator avoids it
    reserved_hms: Optional[tuple[int, int, int]] = None
    if args.first_in_minutes is not None:
        _override = now_local + timedelta(minutes=args.first_in_minutes)
        reserved_hms = (_override.hour, _override.minute, _override.second)

    raw_slots = generate_window_slots(
        rng=rng,
        tz=tz,
        start_date=start_date,
        end_date=end_date,
        windows=windows,
        unique_clock_times=args.unique_clock_times,
        reserved_hms=reserved_hms,
    )
    slot_count = len(raw_slots)
    log.info(f"  {slot_count} window slot(s) generated ({start_date} → {end_date} exclusive)")

    # Apply first_in_minutes: drop window slots at/before the override, then prepend it
    if args.first_in_minutes is not None:
        first_override = now_local + timedelta(minutes=args.first_in_minutes)
        slots = [s for s in raw_slots if s > first_override]
        slots = [first_override] + slots
    else:
        slots = raw_slots

    # --- Pair content with slots ---------------------------------------------
    pairs: list[tuple[dict, datetime]] = list(zip(unblocked, slots))
    no_slot_items = unblocked[len(slots):]
    unused_slots = max(0, len(slots) - len(unblocked))

    if no_slot_items:
        log.warning(
            f"{len(unblocked)} selected item(s) but only {len(slots)} slot(s) available — "
            f"{len(no_slot_items)} item(s) will not be scheduled."
        )
    if unused_slots:
        log.info(f"  {unused_slots} slot(s) will go unused (more slots than content items)")

    # --- Uniqueness check ----------------------------------------------------
    all_hms = [(dt.hour, dt.minute, dt.second) for _, dt in pairs]
    times_unique = len(all_hms) == len(set(all_hms))
    if not times_unique:
        log.warning("Duplicate HH:MM:SS values detected in the generated schedule.")

    # --- Build preview -------------------------------------------------------
    preview_rows: list[dict] = []

    for c in skipped_queued:
        preview_rows.append({
            "title": c["title"],
            "media_type": c.get("media_type", ""),
            "content_status": c["content_status"],
            "scheduled_at_utc": None,
            "action": "skipped — already queued",
        })

    action_verb = "will schedule" if args.execute else "would schedule"
    for c, slot_dt in pairs:
        preview_rows.append({
            "title": c["title"],
            "media_type": c.get("media_type", ""),
            "content_status": c["content_status"],
            "content_id": c["id"],
            "scheduled_at_utc": slot_dt.astimezone(timezone.utc).isoformat(),
            "action": action_verb,
        })

    for c in no_slot_items:
        preview_rows.append({
            "title": c["title"],
            "media_type": c.get("media_type", ""),
            "content_status": c["content_status"],
            "scheduled_at_utc": None,
            "action": "skipped — no slot in window",
        })

    print_preview(preview_rows, tz)

    # --- Execute -------------------------------------------------------------
    inserted = 0
    failed = 0

    if args.execute:
        log.info(f"Inserting {len(pairs)} queue row(s) into ig_publishing_queue...")
        for c, slot_dt in pairs:
            slot_utc_iso = slot_dt.astimezone(timezone.utc).isoformat()
            try:
                supabase.table("ig_publishing_queue").insert({
                    "content_id": c["id"],
                    "queue_status": "scheduled",
                    "scheduled_at": slot_utc_iso,
                    "max_attempts": MAX_ATTEMPTS,
                    "notes": QUEUE_NOTES,
                }).execute()
                inserted += 1
                log.info(f"  ✓ {c['title']!r}  →  {slot_utc_iso}")
            except Exception as exc:
                failed += 1
                log.error(f"  ✗ Failed to insert {c['title']!r}: {exc}")

    first_slot = pairs[0][1] if pairs else None
    last_slot  = pairs[-1][1] if pairs else None

    print_summary(
        total_eligible=len(all_content),
        skipped_prefix=skipped_prefix_count,
        skipped_queued=len(skipped_queued),
        selected_count=len(unblocked),
        slot_count=slot_count,
        unused_slots=unused_slots,
        no_slot=len(no_slot_items),
        to_schedule=len(pairs),
        inserted=inserted,
        failed=failed,
        first_slot=first_slot,
        last_slot=last_slot,
        tz=tz,
        execute=args.execute,
        times_unique=times_unique,
    )


if __name__ == "__main__":
    main()
